# Generated by Django 4.2.4 on 2023-08-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esgscore',
            old_name='total_croporations',
            new_name='total_industries',
        ),
    ]
